activities_manager:
    resource: "@ActivitiesManagerBundle/Resources/config/routing.yml"
    prefix:   /

rewards_manager:
    resource: "@RewardsManagerBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

dashboard_route:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
