rewards_manager:
    resource: "@RewardsManagerBundle/Resources/config/routing.yml"
    prefix:   /rewards

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /dashboard

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

dashboard:
    path:      /dashboard
    defaults:  { _controller: UserBundle:Dashboard:index }
