# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
             entity: { class: UserBundle\Entity\User, property: username }

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        admin:
            pattern:    ^/
            # pattern:    /.*
            anonymous: ~
            form_login:
                login_path:  /login
                check_path:  /login_check
                default_target_path: /dashboard
                success_handler: user.component.authentication.handler.login_handler
            logout:
                path:    /logout
                target:  /login
        default:
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard, roles: ROLE_USER }

    encoders:
        UserBundle\Entity\User:
            algorithm: md5
            encode_as_base64: false
            iterations: 0