login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Login:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

dashboard:
    path:      /dashboard
    defaults:  { _controller: UserBundle:Dashboard:index }

scrumdashboard:
    path:      /scrumdashboard
    defaults:  { _controller: UserBundle:Dashboard:scrumdashboard }

send_points:
    pattern:   /send_points
    defaults:  { _controller: UserBundle:Dashboard:sendpoints }