login:
    pattern:   /login
    defaults:  { _controller: UserBundle:Login:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout

dashboard:
    path:      /dashboard
    defaults:  { _controller: UserBundle:Dashboard:index }

manager:
    path:      /manager
    defaults:  { _controller: UserBundle:Dashboard:manager }

send_points:
    pattern:   /send_points
    defaults:  { _controller: UserBundle:Dashboard:sendpoints }