activities:
    path: /activities
    defaults: { _controller: "ActivitiesManagerBundle:Activities:index" }

activities_new:
    path: /activities/new
    defaults: { _controller: "ActivitiesManagerBundle:Activities:new" }
