activities:
    path: /activities
    defaults: { _controller: "ActivitiesManagerBundle:Activities:index" }

activities_show:
    path: /activities/show/{id}
    defaults: { _controller: "ActivitiesManagerBundle:Activities:show" }
