rewards:
    path: /rewards
    defaults: { _controller: "RewardsManagerBundle:Rewards:index" }

rewards_show:
    path: /rewards/show/{id}
    defaults: { _controller: "RewardsManagerBundle:Rewards:show" }

rewards_new:
    path: /rewards/new
    defaults: { _controller: "RewardsManagerBundle:Rewards:new" }

rewards_create:
    path: /rewards/create
    defaults: { _controller: "RewardsManagerBundle:Rewards:create" }
    requirements: { _method: post }

rewards_edit:
    path: /rewards/edit/{id}
    defaults: { _controller: "RewardsManagerBundle:Rewards:edit" }

rewards_update:
    path: /rewards/update/{id}
    defaults: { _controller: "RewardsManagerBundle:Rewards:update" }
    requirements: { _method: post|put }

rewards_delete:
    path: /rewards/delete/{id}
    defaults: { _controller: "RewardsManagerBundle:Rewards:delete" }
    requirements: { _method: post|delete }
